name: room_rental_app
description: NestFinder - Ứng dụng quản lý phòng trọ
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8

    # State Management & Hooks
    hooks_riverpod: any
    flutter_riverpod: any
    flutter_hooks: any

    # Navigation
    go_router: any

    # Utilities
    intl: any

    # Firebase
    firebase_core: any
    cloud_firestore: any

dev_dependencies:
    flutter_test:
        sdk: flutter

    # --- BỘ CÔNG CỤ KIỂM THỬ (UNIT TEST & PERFORMANCE) ---
    integration_test:
        sdk: flutter
    fake_cloud_firestore: ^2.4.3

    flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
    uses-material-design: true
